# Generated by Django 5.1.6 on 2025-02-27 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'verbose_name': 'ingredient', 'verbose_name_plural': 'ingredients'},
        ),
        migrations.AlterModelOptions(
            name='recipe',
            options={'verbose_name': 'recipe', 'verbose_name_plural': 'recipes'},
        ),
        migrations.AlterModelOptions(
            name='recipeingredient',
            options={'verbose_name': 'recipe ingredient', 'verbose_name_plural': 'recipe ingredients'},
        ),
        migrations.AlterUniqueTogether(
            name='ingredient',
            unique_together={('name',)},
        ),
        migrations.AlterUniqueTogether(
            name='recipe',
            unique_together={('name',)},
        ),
    ]
